env:
    env_name: &env_name "HalfCheetah-v4"
    record: False
    seed: &seed [1, 2, 3]
    min_expected_reward: 200

model_training:
    num_episodes_eval: 5
    record_freq: 5
    summary_freq: 1
    use_baseline: &use_baseline False
    normalize_advantage: True
    device: "gpu" # cpu/gpu
    compile: False
    compile_mode: "default"

hyper_params: 
    max_ep_len: 1000 # maximum episode length (Note: this value must be strictly less than or equal to our batch size)
    num_batches: 100 # number of batches trained on
    batch_size: 50000 # number of steps used to compute each policy update
    learning_rate: 0.03
    gamma: 0.9 # the discount factor
    n_layers: 2
    layer_size: 64

output:
    output_path: &output_path !join ["results/", *env_name, "-{}-", *use_baseline]
    model_output: !join [*output_path, "/model.weights.pt"]
    log_path: !join [*output_path, "/log.txt"]
    scores_output: !join [*output_path, "/scores.npy"]
    plot_output: !join [*output_path, "/scores.png"]
    record_path: *output_path